#!/usr/bin/env zsh

# Define base dirs to search
DIRS=(
    "$HOME"
    "$HOME/dev"
)

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(
        (
            printf "%s\n" "$HOME"
            fd . ${DIRS[@]} --type d --max-depth 1 --full-path
        ) | sed "s|^$HOME/||" \
          | fzf --prompt "Select directory: "
    )
    [[ $selected ]] && selected="$HOME/$selected"
fi

[[ -z $selected ]] && exit 0

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
fi

if [[ -z $TMUX ]]; then
    tmux attach -t "$selected_name"
else
    tmux switch-client -t "$selected_name"
fi
